baseurl = "/"
title = "CityU Wang Lab"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Enable Emoji 
enableEmoji=true
# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Members"
    url  = "/members/members"
    weight = 2
    identifier = "Members"
    
[[menu.main]]
    name = "Current"
    url  = "/members/members"
    weight = 1
    parent = "Members"
    
[[menu.main]]
    name = "Alumni"
    url  = "/members/alumni"
    weight = 2
    parent = "Members"
    

[[menu.main]]
    name = "Publications"
    url  = "/blog/1208all"
    weight = 3
    
[[menu.main]]
    name = "News"
    url  = "/news/news"
    weight = 4.5
    
[[menu.main]]
    name = "Gallery"
    url  = "/galary/galary"
    weight = 5
    
[[menu.main]]
    name = "Resources"
    url  = "/faq/"
    weight = 4
    identifier = "Resources1"

[[menu.main]]
    name = "Overview"
    url  = "/faq/"
    weight = 1
    parent = "Resources1"
    
[[menu.main]]
  weight = 2
  name   = "DeepCC"
  url    = "https://cityuhk-compbio.github.io/deepcc_online/"
  parent = "Resources1"  

[[menu.main]]
  weight = 3
  name   = "HTSanalyzeR"
  url    = "https://htsanalyzer2.netlify.com/"
  parent = "Resources1"
  
[[menu.main]]
  weight = 4
  name = "PAGnet"
  url  = "/PAGnet2/"
  parent = "Resources1"
  
[[menu.main]]
  weight = 5
  name = "PSRnet"
  url  = "/PSRnet/"
  parent = "Resources1"
  
[[menu.main]]
  weight = 6
  name = "CRC-SPA"
  url  = "/CRC_SPA/"
  parent = "Resources1"

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/sanka4rea/XinW_lab"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/Publications/"
    author = "Lin Qi"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyD3AGpKDAfo_LjBRHd-YkYmMjBDlIHfdlo"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    #email = "xin.wang@cityu.edu.hk"

    about_us = "<p>The homepage of Prof. XinWang's Lab in department of Biomedical Science of City University HongKong.</p>"
    copyright = "Copyright (c) 2018 - 2022, Lin Qi of Prof.Xin Wang's Lab. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "May 25, 2018"

    logo = "img/logo4.png"
    address = """<p>Room 315, Block 2
        <br>Rm 124031, 10/F Clinical Sciences Building
        <br>Prince of Wales Hospital
        <br>Department of Surgery
        <br>The Chinese University of Hong Kong
        <br>Sha Ting
        <br><strong>Hong Kong</strong>
        <br>Phone:(852)3505 2746
        
      </p>
      """
    latitude = "22.37966"
    longitude = "114.20097"

#[Permalinks]
   # blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # top carousel
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    #members
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Members"
    subtitle = "**We always welcome outsanding bioinformatics students to join our lab. Please see <u>**Contact**</u> for details.**"

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # collaborations
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Collaborations"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Recent Publications"
    subtitle = " "

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]